### ISSUE TITLE
How to create custom Pattern_Preset

### ISSUE THREAD

**Issue by jeychandar** [RobotecAI/RGLGazeboPlugin#22]
@adamdbrw Hi. I am new to this. I have used your repo and it works perfectly I am able to visualize sonomo_with_rgl.sdf and also you have velodyne, hesaipandar and ouster-64 binary file in lidar_patterns directory. Could you help me out how to create own pattern preset for ouster os1-128. Does it have any direct implementation code using the specification of os1-128 into sdf. Thanks in advance.

**Comment by PawelLiberadzki** [comment]
Hi @jeychandar! Please take a look at [this](https://github.com/RobotecAI/RGLGazeboPlugin#pattern-types) section on the main page, specifically the part about **pattern_preset_path**. In order to make your own pattern preset you have to create a binary file, that contains 3x4 matrix data for each ray casted, without any additional characters in between. I am not aware how this pattern looks for os1-128 - the simpliest way to approach this issue would be to refer to this lidar's documentation (that's how currently available patterns were made).

**Comment by jeychandar** [comment]
@PawelLiberadzki Thankyou for your response. I will check it out sir.
